[package]
name = "oxi_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.51.0"
cgmath = "0.18.0"
thiserror = "1.0.31"
log = "0.4.17"